### ISSUE TITLE
"disable grayscale mode for selected apps" is system-wide, not for selected apps

### ISSUE THREAD

**Issue by johanthebiologist** [rkbhochalya/grayscale-mode#5]
If I check "disable grayscale mode for Finder", it doesn't mean that it's just disabled for Finder. What ends up happening is that I can't enable grayscale mode if Finder is activated. Even if many other apps are also shown on the screen, they don't become grayscale. So in reality, it's not "disable grayscale mode for selected apps", the better definition would be "disable grayscale mode system-wide when selected apps are activated".

Could we get a feature that would match "disable grayscale mode for Finder"? If Finder, Safari, and Notes are shown on the screen, and I have checked "disable grayscale mode for Finder", it means that Safari and Notes would be gray scale, while Finder would remain in colors.

**Comment by rkbhochalya** [comment]
@johanthebiologist I wanted this myself as well but unfortunately as far as I know there is no API to selectively apply Grayscale Filter to apps or part of the screen. We can only turn it on/off globally. Maybe I should update the option to say something like "Disable when Finder is active".

**Comment by johanthebiologist** [comment]
That would make it much more clear for me at least!
